linters:
  # disable-all: false
  enable-all: true
  # enable:
  disable:
    - funlen
    - exportloopref
    - lll # NOTE: configure length larger?
    - cyclop
    - depguard
    - mnd
    - godox
    - varnamelen
    - gochecknoinits
    - gocognit
    - gochecknoglobals
    - execinquery
    - gomnd

    # TODO: enable these one-by-one and fix
    - err113
    - wrapcheck
    - exhaustruct
    - paralleltest
    - contextcheck
    - gosec
