linters:
  # disable-all: false
  enable-all: true
  # enable:
  disable:
    - funlen
    - exportloopref
    - lll # NOTE: configure length larger?
    - cyclop
    - depguard
    - mnd
    - godox
    - varnamelen
    - gochecknoinits
    - gocognit
    - gochecknoglobals

    # TODO: enable these one-by-one and fix
    - testifylint
    - err113
    - wrapcheck
    - exhaustruct
    - ineffassign
    - paralleltest
    - stylecheck
    - sqlclosecheck
    - rowserrcheck
    - nonamedreturns
    - contextcheck
    - gosec
    - errcheck
