package web

var labels = map[string]string{
	"LEFT_SHIFT":  "⇧",
	"LSHFT":       "⇧",
	"RIGHT_SHIFT": "R⇧",
	"RSHFT":       "R⇧",
	"LCTRL":       "^",
	"RCTRL":       "⌃",
	"RET":         "↵",
	"LCMD":        "⌘",
	"RCMD":        "⌘",
	"LALT":        "⌥",
	"RALT":        "⌥",
	"BSPC":        "⌫",
	"SPACE":       "␣",
	"TAB":         "⇥",

	"RIGHT_ARROW": "→",
	"RIGHT":       "→",
	"LEFT_ARROW":  "←",
	"LEFT":        "←",
	"UP_ARROW":    "↑",
	"DOWN_ARROW":  "↓",
	"EQUAL":       "=",
	"N1":          "1",
	"N2":          "2",
	"N3":          "3",
	"N4":          "4",
	"N5":          "5",
	"N6":          "6",
	"N7":          "7",
	"N8":          "8",
	"N9":          "9",
	"N0":          "0",
	"COMMA":       ",",
	"LBKT":        "[",
	"RBKT":        "]",
	"DOT":         ".",
	"SEMI":        ":",
	"BSLH":        "\\",
	"FSLH":        "/",
	"SQT":         "'",
	"MINUS":       "-",
	"GRAVE":       "`",

	// TODO: this is a hack, need to rethink combo parsing.
	"LS(LALT)": "⇧+⌥",
}
